artifactory:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - edge.kube-lab.xyz
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
      ingress.kubernetes.io/force-ssl-redirect: "true"
    tls:
      - secretName: edge.kube-lab.xyz
        hosts:
          - "edge.kube-lab.xyz"
  nginx:
    enabled: false

rabbitmq:
  enabled: false
redis:
  enabled: false
xray:
  enabled: false
distribution:
  enabled: false
insight:
  enabled: false
pipelines:
  enabled: false
